# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WSScrollTabBarController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WSScrollTabBarController

pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'WSScrollAnimationTransition', '~> 0.0.1'

end
